### PR TITLE
Fix for Django 4.0 removed functions

### PR DESCRIPTION
**Pull request by fraimondo**
This PR makes is compatible with Django 4.0.

### CODE REVIEW

**Comment by morlandi** [comment]
@fraimondo I tried to merge this PR but got the following exception:

```
  File "/Users/morlandi/Projects/github_public/django-ajax-datatable/ajax_datatable/views.py", line 371, in dispatch
    if request.accepts('application/json'):
AttributeError: 'WSGIRequest' object has no attribute 'accepts'
```

runnng the example project with Django v 3.0.8 and Python 3.8.11

By inspecting the requests namespaces, accepts() seems to be missing, indeed:

ipdb> dir(request)
['COOKIES', 'FILES', 'GET', 'META', 'POST', 'REQUEST', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_body', '_current_scheme_host', '_encoding', '_files', '_get_full_path', '_get_post', '_get_raw_host', '_get_scheme', '_initialize_handlers', '_load_post_and_files', '_mark_post_parse_error', '_messages', '_post', '_read_started', '_set_content_type_params', '_set_post', '_stream', '_upload_handlers', 'body', 'build_absolute_uri', 'close', 'content_params', 'content_type', 'encoding', 'environ', 'get_full_path', 'get_full_path_info', 'get_host', 'get_port', 'get_raw_uri', 'get_signed_cookie', 'headers', 'is_ajax', 'is_secure', 'method', 'parse_file_upload', 'path', 'path_info', 'read', 'readline', 'readlines', 'resolver_match', 'scheme', 'session', 'upload_handlers', 'user']


Any suggestion ?

**Comment by fraimondo** [comment]
Indeed I just figured out it's specific for Django 4.0. I can think of creating `is_ajax` in `utils.py` and doing the `if` there.

**Comment by PetrDlouhy** [comment]
@fraimondo According to https://stackoverflow.com/questions/63629935/django-3-1-and-is-ajax I fixed this with following function in `django-experiments` project:
```python
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
```

**Comment by fraimondo** [comment]
That was my plan, but I did not have time to take care of that yet. I’ll do it soon.

**Comment by morlandi** [comment]
never mind, take your time 😉

**Comment by morlandi** [comment]
I finally opted for this:

```
        try:
            is_ajax_request = request.accepts("application/json")
        except AttributeError as e:
            # Django < 4.0
            is_ajax_request = request.is_ajax()

        if is_ajax_request:
            ...
```

**Pull request closed without merging**
